version: '3.9'

services:
  db:
    container_name: django_demo_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: django_app_demo
    image: django_demo:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  pgdata: